= HIGHLIGHT LANGUAGE SERVER PROTOCOL CLIENT
André Simon
:revdate: January 2021
:lang: en
:toc: left
:toc-title: Contents
:toclevels: 4
:sectnums:
:sectnumlevels: 2
:sectanchors:
// Misc Settings:
:experimental: true
:icons: font
:linkattrs: true


== LSP SUPPORT

Starting with version 4.0, highlight will use the LSP protocol to enhance
its output.

What does this mean?

Many editors make use of "Language Servers" to get syntax information of various
programming languages without the need to implement a deep understanding of the
files'' syntax they process. Most prominent editor using LSP is VSCode.
A lot of language servers are designed and tested for this editor, since MS
published the LSP specification and VSCode is the reference. Other well known
editors with LSP support are Kate, vim, Emacs and Eclipse.

More information about LSP and editor support:
https://langserver.org/

Highlight will also make use of the LSP interface to access syntax specific
information. Since a general highlighter cannot have a deep understanding of
the code''s meaning this will improve the highlighting quality.

Several beta releases are planned to introduce these features:

* add enhanced tooltips using hover requests (implemented)
* add semantic highlighting (some parts are implemented)
* add rainbow highlighting (tbd)
* add syntax error highlighting (some parts are implemented)


== PROFILES

Language servers are configured in lsp.conf:

+
..........................................................................

Servers = {

  { Server="clangd", Exec="clangd", Syntax="c", Options={"--log=error"} },
  { Server="ccls", Exec="ccls", Syntax="c", Options={"-v=-3", "--"} },
  { Server="ccls-objc", Exec="ccls", Syntax="objc", Options={"-v=-3", "--"} },

  { Server="gopls", Exec="gopls", Syntax="go", Options={} },

  { Server="rls", Exec="rls", Syntax="rust", Options={} },
  { Server="rust-analyzer", Exec="rust-analyzer", Syntax="rust", Delay=250, Options={} },

  { Server="pyls", Exec="pyls", Syntax="python", Options={"--check-parent-process"} },

  { Server="R", Exec="R", Syntax="r", Options={"--slave", "-e", "languageserver::run()"} },

  { Server="clangd-win", Exec="F:\\LLVM\\bin\\clangd.exe", Syntax="c", Options={"--log=error"} },

}
..........................................................................

The profile settings here may be set with the corresponding --ls-* options
(see highlight -h for details).

== OPTIONS

Command line options:
+
..........................................................................
Language Server options (*tbd):

    --ls-profile=<server>      read LSP configuration from lsp.conf
    --ls-delay=<ms>            set server initialization delay

    --ls-exec=<bin>            set server executable name
    --ls-option=<option>       set server CLI option (can be repeated)
    --ls-hover                 execute hover requests (HTML output only)
    --ls-semantic              retrieve semantic token types (requires LSP 3.16)
    --ls-syntax=<lang>         set syntax which is understood by the server
    --ls-rainbow *
    --ls-workspace=<dir>       set workspace directory to init. the server
..........................................................................


== THEMES

All base16 themes have a new section to define semantic token styles. The
types use the same identifiers which are reported by the language server.
If the server reports a token type not listed here, it will be ignored.

+
..........................................................................
-- new LSP based elements:

SemanticTokenTypes  = {
  { Type = 'type', Style = Keywords[2] },
  { Type = 'class', Style =  Keywords[1] },
  { Type = 'struct', Style =  Keywords[4] },
  { Type = 'interface', Style = Keywords[1] },
  { Type = 'parameter', Style = Keywords[5] },
  { Type = 'variable', Style = Keywords[6] },
  { Type = 'enumMember', Style = Keywords[6] },
  { Type = 'function', Style = Keywords[3] },
  { Type = 'method', Style = Keywords[3] },
  { Type = 'keyword', Style =  Keywords[1]},
  { Type = 'number', Style = Number },
  { Type = 'regexp', Style = String },
  { Type = 'operator', Style = Operator },
}
..........................................................................

Find all lsp enabled themes with `highlight --list-scripts=themes --list-cat=lsp`

Default themes will be enhanced later.

These themes are currently adapted for semantic tokens:

edit-kwrite
greenlcd
base16/3024

Others might looks poor.

Additional elements to describe token modifiers will be added in a later release.

=== Example invocation:
+
..........................................................................

highlight  -I --ls-profile ccls --ls-workspace '/home/andre/Projekte/c' /home/andre/Projekte/c/re.cpp --out-format html  --ls-hover > /home/andre/Projekte/c/re.cpp.ccls.html

highlight --ls-profile rls --ls-workspace '/home/andre/Projekte/rust/hello_world' /home/andre/Projekte/rust/hello_world/src/main.rs --outdir ~/test_out
..........................................................................

The GUI offers an LSP tab to enable these options.

=== Example invocation:

Run this command to find themes with semantic style attributes:
+
..........................................................................
highlight --list-scripts=themes --list-cat=lsp
..........................................................................

// EOF //
